version: '3.4'

services:
  dockercplex:
    image: java_app_debug
    build:
      context: ./java_app
      dockerfile: ./java_app/Dockerfile
    environment:
      JAVA_OPTS: -agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=5005,quiet=y
    ports:
      - 3000:3000
      - 5005:5005
