version: '3.4'

services:
    cplex:
        build: ./cplex

    docplex:
        build: ./docplex
        depends_on: 
            - cplex

    java_app:
        build: ./java_app
        depends_on:
            - cplex
